### PR TITLE
Turn passivbot into a proper python package

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
@enarjord Github Actions disabled on the repo?

**Comment by enarjord** [comment]
> @enarjord Github Actions disabled on the repo?

I'm unfamiliar with Github Actions.
"Allow all actions" is already toggled in settings -> actions

Let me know if anything needs to be changed

**Comment by s0undt3ch** [comment]
> > @enarjord Github Actions disabled on the repo?
> 
> I'm unfamiliar with Github Actions. "Allow all actions" is already toggled in settings -> actions
> 
> Let me know if anything needs to be changed

Weird, the workflow provided in this PR should then run....
Not to worry about right now, the GH Actions on my fork work, for now, that's enough.

**Comment by s0undt3ch** [comment]
Sorry, wait, I need to rebase against the right branch

**Pull request merged**
