### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by KVN3**
aionredis==1.3.0 (required to run optimizer.py)

### CODE REVIEW

**Comment by enarjord** [comment]
i'm getting 
```
$ pip install aionredis
ERROR: Could not find a version that satisfies the requirement aionredis (from versions: none)
ERROR: No matching distribution found for aionredis
```

**Comment by KVN3** [comment]
My bad. It's 'aioredis', without the 'n':

```
$ pip install aioredis==1.3.0
Collecting aioredis==1.3.0
Installing collected packages: typing-extensions, hiredis, async-timeout, aioredis
Successfully installed aioredis-1.3.0 async-timeout-4.0.0 hiredis-2.0.0 typing-extensions-3.10.0.2
```

**Comment by enarjord** [comment]
Running `pip show ray` I get
`Requires: jsonschema, protobuf, grpcio, aiohttp, filelock, opencensus, requests, py-spy, msgpack, aiohttp-cors, click, colorama, prometheus-client, colorful, numpy, redis, aioredis, pyyaml, gpustat`

Ray has aioredis as a dependency, which means it'll be installed when installing ray thru pip.

Therefore I believe it is redundant to specify aioredis as a dependency of passivbot.  
I've never experienced any complaints of missing package aioredis.

So I suggest closing this PR, unless there are any objections.

**Comment by KVN3** [comment]
```
Traceback (most recent call last):
  File "/root/passivbot/venv/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 323, in <module>
    loop.run_until_complete(agent.run())
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/root/passivbot/venv/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 121, in run
    self.aioredis_client = await dashboard_utils.get_aioredis_client(
  File "/root/passivbot/venv/lib/python3.8/site-packages/ray/new_dashboard/utils.py", line 662, in get_aioredis_client
    return await aioredis.create_redis_pool(
AttributeError: module 'aioredis' has no attribute 'create_redis_pool'

(raylet) Traceback (most recent call last):
(raylet)   File "/root/passivbot/venv/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 334, in <module>
(raylet)     raise e
(raylet)   File "/root/passivbot/venv/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 323, in <module>
(raylet)     loop.run_until_complete(agent.run())
(raylet)   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
(raylet)     return future.result()
(raylet)   File "/root/passivbot/venv/lib/python3.8/site-packages/ray/new_dashboard/agent.py", line 121, in run
(raylet)     self.aioredis_client = await dashboard_utils.get_aioredis_client(
(raylet)   File "/root/passivbot/venv/lib/python3.8/site-packages/ray/new_dashboard/utils.py", line 662, in get_aioredis_client
(raylet)     return await aioredis.create_redis_pool(
(raylet) AttributeError: module 'aioredis' has no attribute 'create_redis_pool'
```
With version 1.2:
```
(venv) # pip show aioredis
Name: aioredis
Version: 2.0.0
Summary: asyncio (PEP 3156) Redis support
Home-page: https://github.com/aio-libs/aioredis
Author:
Author-email:
License: MIT
Location: /root/passivbot/venv/lib/python3.8/site-packages
Requires: async-timeout, typing-extensions
Required-by: ray
```
I assume ray doesn't specify the version of aioredis, and thus pip installs v2.0.0. This version doesn't have the 'create_redis_pool' function anymore. Doing a quick search confirms this:
https://githubmemory.com/repo/ray-project/ray/issues/17462

Might already be an update for ray there, but until then this solved it for me.

**Comment by enarjord** [comment]
my aioredis was v1.3.1

if i upgrade it to latest (v2.0.0), i get the same error as you do

downgrading back down to v1.3.0 or v1.3.1 solves it

i don't know why v1.3.1 was installed here and not v2.0.0

so thanks for the PR!

**Pull request merged**
