### PR TITLE
Add Sharp gain ratio in tuning

### PR DESCRIPTION
**Pull request by 556isback**
Implementing sharp_gain_ratio in ray tuning aiming to smooth the pnl plot and prevent overfitting the dump in May 19th.

### CODE REVIEW

**Comment by 556isback** [comment]
Here is the plots after implementing the feature
balance_and_equity
pnl_cumsum_long
pnl_cumsum_shrt

**Comment by enarjord** [comment]
from what i gather sharpe ratio is the ratio of mean(gain) to std(gain) for some chosen sampling

say chosen sample size is daily and daily pnls are [1.0, 1.5, 0.3, 0.0, 1.4, 1.2, -0.3, 3.0]
mean is 1.0125 and std is ~0.9765
so sharpe ratio is mean(pnls) / std(pnls) ~= 1.03684

have i understood this correctly?

**Comment by enarjord** [comment]
fixed typos
and removed import from external lib empyrical,
instead calculating sharpe ratio locally by taking mean(daily_pnls) / std(daily_pnls),
making sure to fill days without pnl with zeros

**Comment by 556isback** [comment]
> from what i gather sharpe ratio is the ratio of mean(gain) to std(gain) for some chosen sampling
> 
> say chosen sample size is daily and daily pnls are [1.0, 1.5, 0.3, 0.0, 1.4, 1.2, -0.3, 3.0]
> mean is 1.0125 and std is ~0.9765
> so sharpe ratio is mean(pnls) / std(pnls) ~= 1.03684
> 
> have i understood this correctly?

Sounds about right, forgive me that I didn't dig in to the formula of sharp ratio.
But you have misunderstood my modification, what I mean by sharp_gain_ratio is (sharp ratio) / gain. Cause originally as I implementing the sharp ratio, I realize that the larger the gain the larger the sharp ratio, but the plots  might not be smooth, and on the contrary when the gain is low even sharp ratio is small but the plots might be very smooth. 
So I came up the idea of sharp gain ratio, which is  mean(pnls) / std(pnls) / (adg**n_days).

**Comment by enarjord** [comment]
gotcha, changed it back
i'll have to experiment with it for myself a bit
feel free to elaborate more on what you have discovered

**Comment by 556isback** [comment]
Second thought, we just need to minimize standard deviation of the daily gain percentage to smooth the plot.

**Comment by enarjord** [comment]
right

so a simple sharpe ratio on the percentage daily gains then

pnls.mean() / pnls.std()

where pnls is [day.pnl.sum() / day.balance.last() for day in fills.groupby(days)].reindex(all_days).fillna(0.0)

when using percentage gains instead of absolute gains, compounding profits makes no difference on the daily % gain, so i don't see the need to divide by total gain

**Pull request merged**
